### ISSUE TITLE
A . at the end of  name is mostly forcing an error

### ISSUE THREAD

**Issue by ppfeufer** [eve-val/nrds-tools#22]
Many alliances or corps have a . at the end of their names. This ends up in an error while checking these entities.

**Comment by jerub** [comment]
Can you suggest an example that has an error?

**Comment by ppfeufer** [comment]
Oh yes, here we go.

xxx Biohazard.  Beltbusters Inc.  Boundary. Violation.  Crimson Wings.

Result:
[05:44:45] Rounon Dax >
   KOS (  0) 
NotKOS (  2) **
 Error (  2) **

[+] Biohazard ( http://kos.cva-eve.org/?q=Biohazard )
[+] Crimson Wings ( http://kos.cva-eve.org/?q=Crimson+Wings )

[?] Beltbusters Inc ( http://kos.cva-eve.org/?q=Beltbusters+Inc )
[?] Boundary. Violation ( http://kos.cva-eve.org/?q=Boundary.+Violation )

And three of them are KOS, see the links
